# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialise.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [ ]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np


#### 2. Print the numpy version and the configuration (★☆☆)

In [ ]:
print(np.__version__)
np.show_config()

2.0.2
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
Compilers:
  c:
    commands: cc
    linker: ld.bfd
    name

#### 3. Create a null vector of size 10 (★☆☆)

In [5]:
v1 = np.array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])      # вручную
v2 = np.zeros(10)

print (v1)
print (v2)

[0 0 0 0 0 0 0 0 0 0]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [11]:
x1 = np.random.rand(1)
x2 = np.random.rand(5)
x3 = np.random.rand(10)

print (x1.nbytes, x2.nbytes, x3.nbytes )

8 40 80


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [12]:
help(np.add)

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

    Add arguments element-wise.

    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array will retain its or

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [13]:
import numpy as np

x = np.zeros(10)
x[4] = 1
print (x)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [14]:
x = np.arange(10, 50)
print (x)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [17]:
x = np.arange(10, 50)

print (x[::-1])

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [20]:
matrix = np.arange(9).reshape(3, 3)
print (matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [27]:
arr = np.array([1,2,0,0,4,0])



arr = np.array([1,2,0,0,4,0])
nonz = np.nonzero(arr)[0]
print (nonz)

[0 1 4]


#### 11. Create a 3x3 identity matrix (★☆☆)

In [29]:
matrix = np.eye(5)
print (matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [5]:
matrix = np.random.random((3, 3, 3))
print (matrix)

[[[0.08474784 0.02985824 0.05140285]
  [0.88731885 0.62067285 0.54572941]
  [0.76176884 0.30421888 0.12940108]]

 [[0.11465694 0.63759751 0.17392725]
  [0.31696548 0.27343645 0.77323737]
  [0.26688177 0.59019112 0.60106316]]

 [[0.43274635 0.21810187 0.24224914]
  [0.79550245 0.69622857 0.770143  ]
  [0.96672082 0.67377837 0.3848444 ]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [11]:
arr = np.random.random((10, 10))
print (arr)
arr.min(), arr.max()

[[0.67995759 0.01458841 0.1858113  0.46083939 0.93494171 0.55045826
  0.07882093 0.81826147 0.35956062 0.01139203]
 [0.54285548 0.37439721 0.81573011 0.44987513 0.30662907 0.28394689
  0.02949731 0.32709547 0.14903487 0.90438944]
 [0.04039406 0.90555698 0.2431281  0.90365808 0.52781593 0.13305096
  0.13680264 0.18854319 0.05578321 0.71233594]
 [0.90629248 0.5596588  0.8388429  0.76540404 0.90472199 0.276431
  0.84347047 0.22245989 0.89053699 0.10541777]
 [0.30110858 0.2008803  0.54338459 0.27402455 0.56870632 0.13538455
  0.17462921 0.05609483 0.3498604  0.09662253]
 [0.46903881 0.27367091 0.82058145 0.23828755 0.00625766 0.84115895
  0.51690382 0.75871956 0.97755908 0.00287765]
 [0.02985467 0.76882754 0.32860229 0.27652311 0.34825651 0.97007223
  0.29747113 0.87454438 0.76596098 0.35500902]
 [0.8821389  0.47209444 0.98512413 0.33974412 0.72583473 0.49095176
  0.62255073 0.16272875 0.01843048 0.16869229]
 [0.94302636 0.38944756 0.78261028 0.31044807 0.41871883 0.42502139
  0.64088325 0

(np.float64(0.0028776537048414985), np.float64(0.9851241335893143))

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [13]:
x = np.random.random(30)
x.mean()

np.float64(0.5211977884743547)

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [15]:
x = np.ones((5, 5))
x[1:-1, 1:-1] = 0
print (x)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [17]:
a = np.ones((3, 3))
b = np.pad(a, pad_width=1, mode='constant', constant_values=0)
print (b)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [19]:
0 * np.nan

nan

In [20]:
np.nan == np.nan

False

In [21]:
np.inf > np.nan

False

In [22]:
np.nan - np.nan

nan

In [23]:
np.nan in set([np.nan])

True

In [24]:
0.3 == 3 * 0.1

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [28]:
x = np.diag([1, 2, 3, 4], k=-1)

print (x)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [29]:
a = np.zeros((8, 8), dtype=int)
a[::2, 1::2] = 1
a[1::2, ::2] = 1

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [30]:
x = 99 // (7*8)
y = (99 // 8) % 7
z = 99 % 8

print (x, y, z)

1 5 3


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [34]:
matrix = np.tile([[0, 1], [1, 0]], (2, 4))
print (matrix)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [38]:
m = np.random.random((5, 5))
# print (m)
m = (m - m.min()) / (m.max() - m.min())
print (m)

[[0.90249213 0.557286   0.30752457 0.24060351 0.        ]
 [0.26037376 0.4626815  0.90741992 0.91740532 0.31676006]
 [0.75208556 0.18995256 0.44695585 0.39011036 0.80906506]
 [0.63631837 0.40321586 0.07224937 0.35424254 0.1340583 ]
 [1.         0.05377495 0.81118355 0.55108935 0.19220759]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [43]:
custom_dtype = np.dtype([("r", np.uint8), ("g", np.uint8), ("b", np.uint8), ("a", np.uint8)])


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [45]:
a = np.random.random((5, 3))
b = np.random.random((3, 2))

c = a @ b
# np.dot(a, b)
# a.dot(b)

print (c)

[[0.83442675 0.65316644]
 [0.64446023 0.44147008]
 [1.07016487 0.81984142]
 [0.69826226 0.55350755]
 [1.16040587 0.96391202]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [51]:
arr = np.arange(10)
arr[(a > 3) & (a < 8)] *= -1
arr


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [2]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [3]:

print ('нелегально писать: Z<Z>Z, Z <- Z')

нелегально писать: Z<Z>Z, Z <- Z


#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [4]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

/tmp/ipykernel_10740/548293649.py:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)
/tmp/ipykernel_10740/548293649.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)
/tmp/ipykernel_10740/548293649.py:3: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-9.22337204e+18])

#### 29. How to round away from zero a float array ? (★☆☆)

In [19]:
x = np.random.rand(10) * 5
print (x)
float_array = np.ceil(np.abs(x))
print (float_array)

[4.32110116 4.01234629 4.2861384  1.40906028 0.28015409 1.79950466
 0.26058863 4.2695066  1.82314265 0.09779397]
[5. 5. 5. 2. 1. 2. 1. 5. 2. 1.]


#### 30. How to find common values between two arrays? (★☆☆)

In [26]:
arr1 = np.random.randint(0, 6, 5)
arr2 = np.random.randint(0, 6, 5)
common_values = np.intersect1d(arr1, arr2)

print (arr1)
print (arr2)
print (common_values)

[4 4 1 2 0]
[1 1 5 4 1]
[1 4]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [5]:
np.seterr(all='ignore')

x = np.array(0) / np.array(0)
print (x)

nan


#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [7]:
np.sqrt(-1) == np.emath.sqrt(-1) #none не не равно ничему

np.False_

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [8]:
today = np.datetime64('today')
yesterday = today - np.timedelta64(1, 'D')
tomorrow = today + np.timedelta64(1, 'D')

print(yesterday, today, tomorrow)

2026-04-28 2026-04-29 2026-04-30


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [9]:
dates = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(dates)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

a += b


a *= -0.5

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [16]:
x = np.random.random(10) * 10

arr1 = np.floor(x)
arr2 = x.astype(int)
arr3 = np.trunc(x)
arr4 = x // 1

print (x)
print (arr1)
print (arr2)
print (arr3)
print (arr4)

[5.40903441 0.91751288 0.63445236 0.22873938 3.26224487 2.27582442
 9.64369147 6.39886467 4.40287744 6.25077254]
[5. 0. 0. 0. 3. 2. 9. 6. 4. 6.]
[5 0 0 0 3 2 9 6 4 6]
[5. 0. 0. 0. 3. 2. 9. 6. 4. 6.]
[5. 0. 0. 0. 3. 2. 9. 6. 4. 6.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [19]:
matrix = np.tile(np.arange(5), (5, 1))
print (matrix)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [22]:
def func():
    for i in range(10):
        yield i

arr = np.fromiter(func(), dtype=int)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [23]:
v = np.linspace(0, 1, 12)[1:-1]
print (v)

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [28]:
v = np.random.rand(10)
v.sort()
print (v)

[0.14273657 0.1592003  0.18740726 0.28544845 0.34536362 0.60382082
 0.62822314 0.67934094 0.72070823 0.87616806]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [ ]:
a = np.random.random(10)

result = sum(a)

#### 42. Consider two random arrays A and B, check if they are equal (★★☆)

#### 43. Make an array immutable (read-only) (★★☆)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

#### 48. Print the minimum and maximum representable values for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) array in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to multiply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extracts a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combination of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)